apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-demo-blue
spec:
  replicas: {{ .Values.blue.replicaCount }}
  selector:
    matchLabels:
      app: sample-demo
      color: blue
  template:
    metadata:
      labels:
        app: sample-demo
        color: blue
    spec:
      containers:
        - name: sample-demo
          image: "{{ .Values.blue.image.repository }}:{{ .Values.blue.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.blue.resources.limits.cpu }}
              memory: {{ .Values.blue.resources.limits.memory }}
            requests:
              cpu: {{ .Values.blue.resources.requests.cpu }}
              memory: {{ .Values.blue.resources.requests.memory }}

