apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-demo-blue  # Dynamically switch between blue/green deployments
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

